aur_packages:
  - zen-browser-bin
  - swaync
  - bluez
  - bluez-utils
  - bluetuith
  - [AI_ASSISTANT]-code-stable
  - rofi-wayland
  - waybar
  - pipewire
  - pipewire-audio
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - awww
  - matugen
  - power-profiles-daemon
  - gtk-layer-shell
  - python-gobject
  - python-cairo
  - wlsunset
  - hypridle
  - brightnessctl
  - wl-clipboard
  - youtube-tui
  - yt-dlp
  - mpv
  - ttf-liberation
  - inter-font
  - noto-fonts
  - noto-fonts-emoji
  - ttf-jetbrains-mono-nerd
  - ttf-cascadia-code-nerd
  - ttf-firacode-nerd
  - ttf-hack-nerd
  - papirus-icon-theme
