-- Generated by matugen — do not edit manually
return {
  base00 = "#191114",               -- main background
  base01 = "#130c0f", -- status line / gutter bg
  base02 = "#261d20",        -- selection / line highlight
  base03 = "#d5c2c7",       -- comments
  base04 = "#9d8c91",                  -- inactive text / line numbers
  base05 = "#eedfe2",               -- default foreground
  base06 = "#eedfe2",            -- brighter foreground
  base07 = "#eedfe2",          -- near-white
  base08 = "#ffb4ab",                    -- red — errors, deleted
  base09 = "#ffdcc5",    -- orange — constants, numbers
  base0A = "#e1bdc9",                -- yellow — classes, types
  base0B = "#f1bb97",                 -- green — strings
  base0C = "#fed9e5",   -- cyan — built-ins, special
  base0D = "#ffb0d0",                  -- blue — functions, headings
  base0E = "#6e334e",        -- purple — keywords
  base0F = "#93000a",          -- muted — deprecated
}
