-- Generated by matugen — do not edit manually
return {
  base00 = "#1b110a",               -- main background
  base01 = "#150c06", -- status line / gutter bg
  base02 = "#332820",   -- selection / line highlight
  base03 = "#a58c7c",                  -- comments
  base04 = "#ddc1af",       -- inactive text / line numbers
  base05 = "#f3dfd2",               -- default foreground
  base06 = "#f3dfd2",            -- brighter foreground
  base07 = "#f3dfd2",          -- near-white
  base08 = "#ffb4ab",                    -- red — errors, deleted
  base09 = "#9ad3ae",                 -- teal — constants, numbers
  base0A = "#b6f0c9",    -- green — classes, types
  base0B = "#b8cea1",                -- olive/green — strings
  base0C = "#d4eabc",   -- light green — built-ins
  base0D = "#bbc3ff",                  -- blue — functions, headings
  base0E = "#dfe0ff",     -- light blue — keywords
  base0F = "#50599a",          -- muted — deprecated
}
