- import_playbook: ./roles/core_packages.yml
- import_playbook: ./roles/desktop_packages.yml
- import_playbook: ./roles/dotfiles.yml
- import_playbook: ./roles/app_cleanup.yml
- import_playbook: ./roles/theming.yml
#- import_playbook: ./roles/login_manager.yml
- import_playbook: ./roles/gpu_drivers.yml
- import_playbook: ./roles/workspace_repos.yml
- import_playbook: ./roles/rust_tools.yml
