- name: install | Install greetd and tuigreet
  community.general.pacman:
    name: "{{ login_manager_packages }}"
    state: present
  become: true

- name: install | Configure greetd
  ansible.builtin.copy:
    dest: /etc/greetd/config.toml
    content: "{{ greetd_config }}"
  become: true

- name: install | Enable greetd service
  ansible.builtin.systemd:
    name: greetd.service
    enabled: true
    daemon_reload: true
  become: true
