general {
    before_sleep_cmd    = hyprctl dispatch dpms off
    after_sleep_cmd     = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout    = 150   # 2.5 min — dim screen
    on-timeout = brightnessctl -s set 10%
    on-resume  = brightnessctl -r
}

listener {
    timeout    = 300   # 5 min — screen off
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
